### PR TITLE
Finished messaging API

### PR DESCRIPTION
**Pull request by garzeah**
I believe this covers everything necessary to get messaging going!

**Updates**
- Coded all routes/controllers regarding conversations
- Updated models

### CODE REVIEW

**Comment by bonnieli** [comment]
I think a merge conflict happened in this PR when you merged it: https://github.com/garzeah/decipher/pull/18/files 

In file `client/.eslintcache` there is a merge conflict commited. 
In that PR, the base is `2-controllers-error-handling` so i don't think it actually got commited to `dev`. If you can confirm that `2-controllers-error-handling` got merged to dev, please pull your latest changes into dev so that this PR reflects new code

**Comment by garzeah** [comment]
Hi Bonnie, I'm a little confused but I just pulled and it said this. I used git status afterwards to see if I could push the new updates but nothing was shown.
Screen Shot 2021-02-10 at 10 07 44 AM

I don't know if this is relevant but I ended up adding .eslintcache to .gitignore. Also, I merged 2-controllers-error-handling with 5-messaging-api after I merged my 2 previous pull requests to master.

**Comment by bonnieli** [comment]
@garzeah do `git pull origin master` or `git merge master` (if you are confident your local master is most up to date)

you want to be explicitly telling git what to pull from. hope that works!

**Comment by garzeah** [comment]
> @garzeah do `git pull origin master` or `git merge master` (if you are confident your local master is most up to date)
> 
> you want to be explicitly telling git what to pull from. hope that works!

Okay, just did that! It seems like everything is working as intended. Is it okay for me to merge this PR?

**Review by bonnieli — APPROVED** [review]
Hm, weird i feel like I reviewed a lot of this code already. Hope we get a more clear picture of changes in PR in the future :) 

Anyhow, approved!

**Pull request merged**
