### PR TITLE
added login and sign up pages

### PR DESCRIPTION
**Pull request by garzeah**
**Updates**
- Added login/signup pages for the front end
- Added a proxy so that the front and back end can work together more easily
- Added files to config and updated server package.json and server.js for heroku deployment
- Changed file structure to make deployment easier

Let me know if there's anything else I could add! I wanted to add the icon shown in the pdf but it wasn't provided in the assets folder. I'm also going to save the "Choose a Primary Language" for a later update once I familiarize myself with the Google Translate API. For the next update, I plan to add Redux, update validation on the Front end and store our input in the back end.

### CODE REVIEW

**Comment by bonnieli** [comment]
I think this branch may be a little out dated? No merge conflicts but I see some of #13 PR file changes in here.

Before you look too deep into Google translate API or redux, look into sockets.io so you can get a simple flow going :) Once you have that piece of the puzzle implemented, redux and Google translate API should be a good next step!

**Comment by garzeah** [comment]
> I think this branch may be a little out dated? No merge conflicts but I see some of #13 PR file changes in here.
> 
> Before you look too deep into Google translate API or redux, look into sockets.io so you can get a simple flow going :) Once you have that piece of the puzzle implemented, redux and Google translate API should be a good next step!

Thanks for the feedback Bonnie! I'll definitely look into WebSockets first before jumping into the Google translate API and redux (thinking of scrapping this and implementing it the react hooks way). Is it okay for me to merge this? I'm a little confused about git merge, conflicts, and what you mean by the branch is outdated. If I update the code in PR#13 and merge that with master, then merge PR#14 with master will I lose some of my progress? I changed the back-end a bit in PR#14 and I'm concerned that if I update PR#13 w/ old format, then PR#14 will overwrite my progress in PR#13. I was thinking of merging this then reopening a new PR to address the concerns in PR#13.

**Comment by bonnieli** [comment]
@garzeah If you take a look at the files changed in this PR, I noticed it also includes the new models that you have in #13 . Since this PR is meant to just restructure things, if you merge this in right now, it would also merge things that are not yet ready for `master`. Your options are to

1. Change the base of this PR so this means that even if it is branched off of #13, when change the base it will only reflect the ongoing changes and if you merge it, it won't affect `master` 
2. Separate out these 2 different PRs since they seem to be quite independent to each other

> If I update the code in PR#13 and merge that with master, then merge PR#14 with master will I lose some of my progress?

You won't, this would actually be fine but this current PR will be blocked by #13 . If it is reliant on #13, you can add a dependency to this PR to properly signify this in the PR

**Comment by garzeah** [comment]
> @garzeah If you take a look at the files changed in this PR, I noticed it also includes the new models that you have in #13 . Since this PR is meant to just restructure things, if you merge this in right now, it would also merge things that are not yet ready for `master`. Your options are to
> 
> 1. Change the base of this PR so this means that even if it is branched off of #13, when change the base it will only reflect the ongoing changes and if you merge it, it won't affect `master`
> 2. Separate out these 2 different PRs since they seem to be quite independent to each other
> 
> > If I update the code in PR#13 and merge that with master, then merge PR#14 with master will I lose some of my progress?
> 
> You won't, this would actually be fine but this current PR will be blocked by #13 . If it is reliant on #13, you can add a dependency to this PR to properly signify this in the PR

Okay thanks Bonnie, I think I get it! I'm going to update PR#13 then proceed to merge it with master, then do the same with PR#14.

**Comment by bonnieli** [comment]
Super! Yep merge #13 in first, after you do that, the files changed in this PR would be more clear. and then you can merge this one in :)

**Pull request merged**
